language: node_js
node_js:
- node
script: npm run cover
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
deploy:
  provider: npm
  skip_cleanup: true
  email: dp-npm@fabiankretzer.de
  on:
    all_branches: true
    tags: true
  api_key:
    secure: orTIAbb4kwS8M3flseq+92WjqwHFEF+SPLyYfNj4IVNo9UY8tJ/I19CXhk9BAVyT23SBPakWoDOKNo9/ojImYeR1Spc5kJd/Jw0jD8PhGH3ZflzZc77WetcGgnc2pAfvRmu3U2LFHXx/Aq82+d81KBrNTiiltDgpuQrwpme75Y/yZafNEuyuKYChgHP8E0dltfJYSXk7H5FuybMiBYnSRLDn6uW90Q+wttGvjQ0sKRp2zjI0SxQxACbhxVG8VIQkkCIE/IO7pm3fL+vGjU3Yxu6JvY7wyn3wInkfsoQb/NkZdLFtRzqJSv5iy7FDw5UFpZAtW3cW7Y4gH33TtF6jQgMOwyY1C65d/JaepSIDLbs996lGvytr3kyt1qB5Hn2Rnt3fUw7CdnWP/U+jDawKzDAGBw9YW4YnBDOs8j7dsS2xmdVsDqxRqY79so7qaHT2rDHrOJ2Zk092zFZRh68uyKZRqNtLnojFy1suXK01Sd9s1gC4Qm/VHs71SsSQZw8EN6lJsNVFilDoEYWrV+mBTjfVUkllU8Nzjl53U4pkCYY6OgM1iycsRP9WY7ZMAmfDVE6wDaaF6BtVAqttnU/XgmKQF4QtNNF1UKJD/9uPqe9kDFT5LsWndylnpmNZRYWWF3V3L5a2s4sSYRciC7NipaJ/t2l9YAl8+wXn9ruupBs=
cache:
  directories:
    - node_modules
